### ISSUE TITLE
Not relevant code in chapter 4 package

### ISSUE THREAD

**Issue by Boiarshinov** [nwangtw/miniStreaming#12]
Hi! I'm reading your book and now i'm on the 4 chapter. 
There was nothing in the book about Toll Booth, but in this repository there is 3 examples about that in ch04 package.
Maybe it is a translation mistake, because I'm reading the russian version of the book, but I didn't found anything about Toll Booth in Manning site either.
Probably that code was left after some book editing.
What do you think about moving these 3 examples to separate package (ch04extra)?
- StreamForkJob
- StreamMergeJob
- StreamSplitJob

**Comment by joshfischer1108** [comment]
Hi @Boiarshinov , I think moving those jobs to separate package is fine. Thank you for the contribution.

**Comment by Boiarshinov** [comment]
I have prepared PR for this migration: https://github.com/nwangtw/GrokkingStreamingSystems/pull/13

**Comment by nwangtw** [comment]
I believe this is resolved. Thanks!
